#!/bin/bash
#PBS -S /bin/bash
#PBS -l select=1:ncpus=48:mem=100gb,walltime=48:00:00
#PBS -N Simulation_Full
#PBS -j oe
#PBS -o outputs/output_simulation.txt

container_img="/u/marchesin/containers/r-geo-phd_v2.0.sif"

echo "Job started on $(date)"
cd ${PBS_O_WORKDIR}
/opt/mox/apptainer/bin/apptainer exec $container_img Rscript scripts/Simulation_Study.R > Simulation_Study.Rout 2>&1

echo "Job finished on $(date)"
